### ISSUE TITLE
Kindly update document and demo project

### ISSUE THREAD

**Issue by abdulKarim002** [hypertrack/quickstart-ios#7]
Hello Guys
I am getting this error 
`"The operation couldn’t be completed. (HyperTrack.CoreError error 1.)"`
while resuming using this     
```
HyperTrack.resumeTracking { (err) in
      print(err?.localizedDescription)
}
```

I tried using the demo project but that also doesn't work
and kindly update the document according to the project

environment detail
- Xcode 10x
- iOS 10x

_Note:- I have enabled location service and activity services_

**Comment by tulushev** [comment]
Hey @abdulKarim002 we've updated the API's and errors. Can you try the new version and see if the issue went away?

**Comment by abdulKarim002** [comment]
@tulushev yeah it works great. thankx
